spring.application.name=addressBookApp

server.port=8090
spring.datasource.username=root
spring.datasource.password=the_arty_villa1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/addressbook_db?useSSL=false
